# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-2022

steps:

- powershell: |
    $configFile = "$(System.DefaultWorkingDirectory)/src/environments/environment.prod.ts"
    $endPoint = "$(endPoint)"
    $apiKey = "$(apiKey)"
    $urlLogin = "$(urlLogin)"
    $urlAccess = "$(urlAccess)"
    $urlFile = "$(urlFile)"
    
    Get-Content $configFile

    #reemplazar
    $contenido =  Get-Content $configFile
    $contenido =  $contenido -replace "#{endPoint}#", $endpoint
    $contenido =  $contenido -replace "#{urlLogin}#", $urlLogin
    $contenido =  $contenido -replace "#{urlAccess}#", $urlAccess
    $contenido =  $contenido -replace "#{urlFile}#", $urlFile
    $contenido =  $contenido -replace "#{apiKey}#", $apiKey

    #guardar contenido
    $contenido | set-Content $configFile
  
  displayName: 'Reemplazar variables en environment.prod.ts'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

- script: npm install -g @angular/cli
  displayName: 'Instalar Angular CLI'

- script: npm install
  displayName: 'Instalar dependencias de Angular'

- script: ng build
  displayName: 'Compilar la aplicación Angular'

- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefactos'
  inputs:
    pathtoPublish: 'dist' # Ruta de la carpeta de compilación de Angular
